// Core types for Journey Generator

export type ExperienceType = 'product' | 'marketing' | 'service';

/**
 * A top-level journey on a model. A model can contain several journeys
 * (for example an airport model has Arrival, Transit, Departure) and each
 * journey has its own Pre-discovery JTBD blueprint — a one-liner that frames what the
 * customer is fundamentally trying to do during that journey. Journey
 * phases, demand spaces, dimensions, and activations are all scoped to a
 * single journey via `JourneyPhase.journeyId`.
 */
export interface Journey {
  id: string;
  name: string;
  jtbdBlueprint: string;
  order: number;
}

export interface JourneyPhase {
  id: string;
  /**
   * The journey this phase belongs to. Optional at the type level only to
   * keep backwards compatibility with pre-multi-journey models loaded
   * from localStorage; the store's migration stamps legacy phases on
   * hydration so in practice every phase in the store has a journeyId.
   */
  journeyId?: string;
  label: string;
  description: string;
  trigger: string; // What event marks entry into this phase
  order: number;
  /**
   * Where this phase came from.
   * - `user`      → user typed or preloaded the phase in the brief (e.g. Dubai Airport example)
   * - `ai`        → generated by the journey-phases endpoint
   * - `discovery` → proposed from discovery evidence/signals
   * Optional for backwards compatibility with older models.
   */
  source?: 'user' | 'ai' | 'discovery';
  /**
   * Which inputs the phase was generated from. Used for badging on the
   * Hypothesis Landscape variant comparison.
   * - `form-only`       → only the structured brief form (industry, business
   *                       description, painPoints…)
   * - `brief-only`      → form + uploaded brief document
   * - `research-backed` → form + uploaded research documents (no brief doc)
   * - `mixed`           → both brief doc and research docs
   * - `signal-backed`   → discovery evidence (post-Capture)
   */
  evidence?: 'form-only' | 'brief-only' | 'research-backed' | 'mixed' | 'signal-backed';
}

export interface DemandSpace {
  id: string;
  /**
   * For phase-scoped demand spaces (default), the FK into JourneyPhase.
   * Cross-cutting demand spaces (`scope === 'cross-cutting'`) carry the
   * sentinel `''` here — they don't belong to any phase. The store keeps
   * cross-cutting demand spaces in `Model.crossCuttingDemandSpaces` so
   * existing per-phase grouping logic stays untouched.
   */
  journeyPhaseId: string;
  label: string; // 2-4 words
  jobToBeDone: string; // "When I [situation], I want to [action], so that [outcome]"
  description?: string; // Optional 2-3 sentences (kept for backwards compatibility)
  order: number;
  /**
   * IDs of `ProblemDiagnostic` rows this JTBD addresses. Populated only
   * when the demand space was generated on the Informed Landscape route
   * (the route passes classified problems into the prompt and the LLM
   * tags each JTBD with the problems it covers). Absent/empty on
   * Hypothesis Landscape demand spaces and pre-provenance demand spaces.
   */
  sourceProblemIds?: string[];
  /**
   * Whether this demand space lives under a journey phase or sits in the
   * cross-cutting silo. Defaults to `'phase'` when absent (backwards
   * compatibility).
   */
  scope?: 'phase' | 'cross-cutting';
}

/**
 * A Circumstance is a composite position across the 5 universal axes
 * (Knowledge, Intent, Composition, Constraint, Moment) plus a narrative
 * JTBD-formatted statement and the Struggle/Progress forces. Each demand
 * space gets exactly 5 Circumstances, and collectively they must cover
 * contrast on every axis (e.g. at least one Novice + one Expert).
 */
export interface Circumstance {
  id: string;
  demandSpaceId: string;
  order: number;
  // Axis tuple — one value per axis
  knowledge: string;     // e.g. "Expert"
  intent: string;        // e.g. "Routine"
  composition: string;   // e.g. "Solo"
  constraint: string;    // e.g. "Time"
  moment: string;        // e.g. "Long-haul business travel"
  // Narrative (assembled as "When I am [context], I want to [action], so that [outcome].")
  context: string;       // "flying alone on a long-haul overnight work trip and already know what content unwinds me"
  action: string;        // "quickly access familiar entertainment options"
  outcome: string;       // "relax fast and make the journey feel shorter"
  // Forces framework
  struggle: string;      // "The system slows me down when I already know what I want."
  progress: string;      // "Get into rest mode quickly and reduce the mental drag of travel."
  // Optional provenance (matches existing signal-backed pattern)
  supportingSignalIds?: string[];
  evidence?: 'signal-backed' | 'brief-only';
}

// Tech stack tool with purpose
export interface TechTool {
  id: string;
  value: string;     // Tool name
  purpose?: string;  // What this tool is used for
}

// Tech stack structured input - each field supports multiple selections
export interface TechStack {
  cloudWarehouse?: TechTool[];     // e.g., Snowflake, BigQuery, Redshift, Databricks
  dataStorage?: TechTool[];        // e.g., AWS S3, Azure Blob, PostgreSQL, MongoDB
  crm?: TechTool[];                // e.g., Salesforce, HubSpot, Microsoft Dynamics
  cdp?: TechTool[];                // e.g., Segment, mParticle, Tealium, Adobe CDP
  cep?: TechTool[];                // e.g., Braze, Emarsys, SFMC, Iterable
  dxp?: TechTool[];                // e.g., Optimizely, Adobe Experience Manager, Sitecore
  aiModels?: TechTool[];           // e.g., GPT-4, Claude, Gemini, Llama
  aiPlatform?: TechTool[];         // e.g., Azure AI Foundry, AWS Bedrock, Vertex AI
}

// Product/channel with description
export interface Product {
  id: string;
  name: string;        // e.g., "Mobile App", "Website", "Kiosk"
  description: string; // What this product/channel does
}

// Target persona
export interface Persona {
  id: string;
  label: string;       // e.g., "Budget-conscious families"
}

// Persona mapping - links personas to demand spaces and circumstances per phase
export interface PersonaPhaseMapping {
  phaseId: string;
  demandSpaceIds: string[];    // Demand spaces in this phase for this persona
  circumstanceIds: string[];   // Circumstances in this phase for this persona
}

export interface PersonaMapping {
  personaId: string;
  mappingsByPhase: PersonaPhaseMapping[];  // Phase-structured mappings (one entry per phase)
}

// User-defined phase (before generation)
export interface CustomJourneyPhase {
  label: string;
  description: string;
  trigger?: string;
}

/**
 * A full brief document the user uploads on the home page (PDF/Word/etc).
 * Parsed text is retained verbatim so downstream prompts can pass the
 * complete context — not just the form fields the user pre-filled from it.
 */
export interface BriefDocument {
  filename: string;
  text: string;            // Parsed plain text (no truncation)
  uploadedAt: Date;
  sizeBytes: number;
  charCount: number;
}

/**
 * A research artifact uploaded in the optional Research step (between
 * Brief and Hypothesis Landscape). Multiple documents are allowed.
 * Each carries an LLM-generated summary so we can compose contextual
 * blends without re-paying for full-text tokens on every downstream call.
 */
/** Structured distillation of a single research artifact. Generated by
 *  /api/summarize-research-doc and stored alongside the verbatim text on
 *  the ResearchDocument so downstream context blends can inject the
 *  substance without paying full-text token costs on every prompt. */
export interface ResearchDocSummary {
  headline?: string;
  evidenceType?: string;
  keyFindings?: string[];
  namedSegments?: string[];
  namedJourneys?: string[];
  painsAndFrictions?: string[];
  opportunitiesOrHypotheses?: string[];
  directQuotes?: string[];
  summary?: string;          // 80-150 word prose distillation (this is what gets injected into prompts)
}

export interface ResearchDocument {
  id: string;
  filename: string;
  text: string;              // Parsed plain text (no truncation)
  summary?: ResearchDocSummary;  // Structured distillation; summary.summary is the injectable prose
  summarizedAt?: Date;
  uploadedAt: Date;
  sizeBytes: number;
}

export interface ModelInput {
  experienceTypes: ExperienceType[];  // Now supports multiple selection
  industry: string;
  businessDescription: string;
  techStack?: TechStack;
  products?: Product[];
  channels?: string[];
  personas?: Persona[];
  painPoints?: string;  // Now a textarea (multi-line)
  customJourneyPhases?: CustomJourneyPhase[];  // Optional: user can mandate phases instead of generating them
  /** Full brief document uploaded on the home page; pre-fills the form
   *  and is passed verbatim to downstream context blends. */
  briefDocument?: BriefDocument;
  /** Research artifacts uploaded in the optional Research step. */
  researchDocuments?: ResearchDocument[];
}

// Activation types - what to do for each Demand Space × Circumstance combination.
// NOTE: Activation generation is currently deferred — the APIs have not yet
// been migrated from the old dimension-value model to the new Circumstance
// model. These types reflect the target shape (one activation per
// Circumstance) even though generation is temporarily disabled in the UI.

// Marketing: 6 CRM levers
export interface MarketingActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  messageDepth: string; // awareness, consideration, action
  urgency: string; // low, medium, high
  channel: string; // email, SMS, push, in-app, etc.
  tone: string; // informative, empathetic, urgent, celebratory
  offer: string; // what to offer
  cadence: string; // frequency and timing
}

// Product: Features that become user stories
export interface ProductActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  feature: string; // feature name
  description: string; // what it does
  userStory: string; // As a... I want... So that...
  priority: 'high' | 'medium' | 'low';
}

// Service: Agent tools and knowledge
export interface ServiceActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  tools: string; // tools/systems to use
  knowledge: string; // knowledge articles to surface
  c360Signals: string; // customer 360 data points to show
  handoffRules: string; // when/how to escalate or transfer
}

/**
 * Which input mix produced a given hypothesis variant. Drives the badge
 * on the variant comparison view and the prompt context blend.
 *
 * - `form-only`     → only the structured brief form
 * - `brief-only`    → only the uploaded brief document
 * - `research-only` → only the uploaded research documents
 * - `form+research` → form + research documents (no brief doc)
 * - `everything`    → form + brief doc + research documents
 */
export type HypothesisBlend =
  | 'form-only'
  | 'brief-only'
  | 'research-only'
  | 'form+research'
  | 'everything';

/**
 * One generated hypothesis landscape variant. The store keeps several of
 * these side by side so the user can compare them; the `isActive` flag
 * marks the one mirrored onto `Model.journeyPhases` for downstream
 * compatibility (existing demand-space / circumstance generation only
 * knows about journeyPhases). `sourceFingerprint` captures a hash of the
 * inputs that produced the variant so we can detect staleness.
 *
 * INVARIANT — "only one landscape is live": when a variant in either
 * `hypothesisVariants` or `informedVariants` is set active, all variants
 * in BOTH arrays must be marked inactive except for the one being
 * activated. The active variant's phases mirror to `Model.journeyPhases`.
 */
export interface HypothesisVariant {
  id: string;
  blend: HypothesisBlend;
  label: string;                      // Display label, e.g. "Form + Research"
  journeyPhases: JourneyPhase[];      // Phases generated for this blend
  generatedAt: Date;
  tokenCost?: number;
  sourceFingerprint: string;
  isActive: boolean;
}

/**
 * Which evidence mix produced a given Informed Landscape variant.
 * Anchored on classified problems (mandatory) plus optional supporting
 * sources.
 *
 * - `problems-only`     → classified problems alone
 * - `problems+brief`    → problems + verbatim client brief
 * - `problems+research` → problems + research summaries
 * - `everything`        → problems + brief + research + form fields
 */
export type InformedBlend =
  | 'problems-only'
  | 'problems+brief'
  | 'problems+research'
  | 'everything';

/**
 * One Informed-landscape variant. Parallel to HypothesisVariant, anchored
 * on classified problems instead of brief/research.
 *
 * INVARIANT — "only one landscape is live": when a variant in either
 * `hypothesisVariants` or `informedVariants` is set active, all other
 * variants in BOTH arrays must be marked inactive. The active variant's
 * phases mirror to `Model.journeyPhases` so the existing demand-space /
 * circumstance cascade keeps working unchanged.
 */
export interface InformedLandscapeVariant {
  id: string;
  blend: InformedBlend;
  label: string;
  journeyPhases: JourneyPhase[];
  generatedAt: Date;
  tokenCost?: number;
  sourceFingerprint: string;
  isActive: boolean;
}

export interface Model {
  id: string;
  input: ModelInput;
  /**
   * Top-level journeys on this model (Arrival / Transit / Departure, etc.).
   * Always present on newly created models. Older models (from before
   * multi-journey support landed) may be missing this field on disk;
   * the store rehydration migrates them into a single default journey.
   */
  journeys: Journey[];
  journeyPhases: JourneyPhase[];
  demandSpaces: DemandSpace[];
  /**
   * Cross-cutting demand spaces — JTBDs that address systemic / cross-
   * cutting problems (those with `affectedPhaseIds: []` in the diagnostics).
   * They do NOT belong to any journey phase and are rendered in their own
   * silo on the Informed Landscape route. Generated by
   * `/api/generate-cross-cutting-demand-spaces`. Optional for backwards
   * compatibility; the store rehydration migration defaults to `[]`.
   */
  crossCuttingDemandSpaces?: DemandSpace[];
  circumstances: Circumstance[]; // 5 composite circumstances per demand space
  marketingActivations: MarketingActivation[];
  productActivations: ProductActivation[];
  serviceActivations: ServiceActivation[];
  personaMappings: PersonaMapping[]; // Persona filtering

  /**
   * All side-by-side hypothesis landscape variants generated for this
   * model. The active one's phases are mirrored to `journeyPhases` so the
   * downstream demand-space / circumstance pipeline keeps working
   * unchanged.
   */
  hypothesisVariants?: HypothesisVariant[];

  /**
   * All side-by-side Informed Landscape variants generated for this
   * model. Built from classified problems (Problem Diagnostics step).
   * The active one's phases are mirrored to `journeyPhases`. See
   * InformedLandscapeVariant doc for the bidirectional active-landscape
   * invariant with `hypothesisVariants`.
   */
  informedVariants?: InformedLandscapeVariant[];

  // Discovery & Signal Mapping (Phase 1)
  discoveryPlan?: DiscoveryPlan;
  evidenceRecords?: Evidence[];
  signals?: Signal[];
  mappings?: Mapping[];
  proposals?: Proposal[];
  discoveryBundle?: DiscoveryBundle;
  currentStep?: ConsultancyStep;

  // Workshop inventory (Plan step)
  workshops?: Workshop[];
  workshopQuestions?: WorkshopQuestion[];

  // Capture-flow gating: hard-locks Findings + Diagnostics tabs until the
  // user has either confirmed Q&A (acknowledging that any edits are
  // baked in) or explicitly skipped it. Exactly one of the two should be
  // set at a time; calling skip clears confirm and vice versa.
  qaConfirmedAt?: Date | null;
  qaSkippedAt?: Date | null;

  // NOTE: Capture & Extraction entities (Upload, TranscriptChunk,
  // Extraction, QuestionAnswer, ExtractedSignal) live in IndexedDB only,
  // not on Model. They're too heavy for localStorage (parsed transcripts
  // + embeddings) and have real relational shape. The store exposes them
  // as a parallel `capture` slice hydrated via the storage adapter.
  // See lib/storage/* and the capture slice in lib/store.ts.

  createdAt: Date;
  updatedAt: Date;
}

// API response types
export interface GenerateJourneyPhasesResponse {
  journeyPhases: Omit<JourneyPhase, 'id' | 'order'>[];
}

// Demand spaces response - no longer includes circumstances.
// `sourceProblemIds` is populated only on the Informed Landscape path
// (when the route is called with `informedProblems`); omitted otherwise.
export interface GenerateDemandSpacesResponse {
  demandSpaces: {
    label: string;
    jobToBeDone: string;
    description?: string;
    sourceProblemIds?: string[];
  }[];
}

/** Response shape for `/api/generate-cross-cutting-demand-spaces`. */
export interface GenerateCrossCuttingDemandSpacesResponse {
  demandSpaces: {
    label: string;
    jobToBeDone: string;
    description?: string;
    sourceProblemIds?: string[];
  }[];
}

// Circumstances response - exactly 5 circumstances per demand space × phase
// crossing. Each circumstance is a composite across all 5 universal axes
// plus a JTBD-formatted narrative and Struggle/Progress forces.
export interface GenerateCircumstancesResponse {
  circumstances: {
    knowledge: string;
    intent: string;
    composition: string;
    constraint: string;
    moment: string;
    context: string;
    action: string;
    outcome: string;
    struggle: string;
    progress: string;
    supportingSignalIds?: string[];
    evidence?: 'signal-backed' | 'brief-only';
  }[];
}

// Activation response types (deferred migration — see note above).
export interface GenerateMarketingActivationsResponse {
  activations: {
    circumstanceLabel: string;
    messageDepth: string;
    urgency: string;
    channel: string;
    tone: string;
    offer: string;
    cadence: string;
  }[];
}

export interface GenerateProductActivationsResponse {
  activations: {
    circumstanceLabel: string;
    feature: string;
    description: string;
    userStory: string;
    priority: string;
  }[];
}

export interface GenerateServiceActivationsResponse {
  activations: {
    circumstanceLabel: string;
    tools: string;
    knowledge: string;
    c360Signals: string;
    handoffRules: string;
  }[];
}

// Persona mapping response
export interface MapPersonasResponse {
  personaMappings: {
    personaId: string;
    mappingsByPhase: {
      phaseId: string;
      demandSpaceIds: string[];
      circumstanceIds: string[];
    }[];
  }[];
}

// ========================================
// Discovery & Signal Mapping Types (Phase 1)
// ========================================

// Evidence types (from discovery-framework skill)
export type EvidenceType = 'interview' | 'workshop' | 'document' | 'quote' | 'metric' | 'observation' | 'artifact';
export type ConfidenceLevel = 'high' | 'medium' | 'low';

export interface Evidence {
  id: string;
  type: EvidenceType;
  department: string;
  source: string;
  date: Date;
  summary: string;
  rawText?: string;
  tags: string[];
  confidence: ConfidenceLevel;
  confidenceReason: string;
  contradicts?: string[]; // Evidence IDs this contradicts
}

// Signal types (from signal-mapping-framework skill)
export type SignalType = 'problem' | 'need' | 'opportunity' | 'gap';

export interface SignalSource {
  evidenceId: string;
  quote?: string;
}

export interface Signal {
  id: string;
  type: SignalType;
  text: string;
  department: string;
  sources: SignalSource[];
  relatedSignalIds?: string[];
  confidence: ConfidenceLevel;
  confidenceReason: string;
  proposedAction?: string;
}

// Discovery Plan types (from discovery-question-generator agent)
export type DiscoveryPriority = 'must-have' | 'should-have' | 'skip';

export interface DiscoveryPlanInterview {
  department: string;
  role: string;
  priority: DiscoveryPriority;
  duration: string;
  questions: string[];
  capture: string[]; // Documents to request
}

export interface DiscoveryPlanWorkshop {
  name: string;
  participants: string[];
  duration: string;
  priority: DiscoveryPriority;
  objective: string;
}

export interface DiscoveryPlanDocument {
  title: string;
  askedOf: string;
  priority: DiscoveryPriority;
}

export interface DiscoveryPlan {
  plan: {
    interviews: DiscoveryPlanInterview[];
    workshops: DiscoveryPlanWorkshop[];
    documents: DiscoveryPlanDocument[];
  };
  coverage: {
    departments: Record<string, DiscoveryPriority>;
    risks: string[];
  };
  timelineEstimate: string;
}

// Mapping & Proposal types (from mapper-agent)
export type MappingTargetKind = 'phase' | 'demandSpace' | 'circumstance' | 'activation';

export interface Mapping {
  signalId: string;
  action: 'map';
  target: {
    kind: MappingTargetKind;
    id: string;
  };
  rationale: string;
  conflictFlag?: boolean;
}

export interface Proposal {
  signalIds: string[];
  action: 'propose';
  kind: MappingTargetKind;
  payload: unknown; // Entity-specific shape (phase, demandSpace, dimension, etc.)
  justification: {
    reasoning: string;
    confidence: ConfidenceLevel;
    confidenceReason: string;
  };
  status: 'proposed';
}

// Discovery Bundle - approved evidence + signals ready for generation
export interface DiscoveryBundle {
  approvedEvidence: Evidence[];
  candidateSignals: {
    problems: Signal[];
    needs: Signal[];
    opportunities: Signal[];
    gaps: Signal[];
  };
  approvedBy: string;
  approvedAt: Date;
}

// Consultancy workflow step
export type ConsultancyStep =
  | 'brief'
  | 'research'
  | 'hypothesis-landscape'
  | 'discovery'
  | 'definition'
  | 'plan'
  | 'capture'
  | 'diagnostics'
  | 'informed-landscape'
  | 'signals'
  | 'review'
  | 'evidenced-landscape';

// ========================================
// Workshop Inventory (Plan step)
// ========================================

export type WorkshopMode = 'onsite' | 'hybrid' | 'remote';
export type WorkshopStatus =
  | 'draft'
  | 'proposed'
  | 'scheduled'
  | 'done'
  | 'skipped';

/** One slot within a workshop's tentative agenda. */
export interface WorkshopAgendaItem {
  id: string;
  label: string;        // "Context-set + role framing"
  duration?: string;    // "15 min", "0:45"
  notes?: string;       // facilitator guidance, sticky-note prompts, etc.
}

/**
 * An attendee slot on a workshop: a **role title** (always) plus an
 * optional list of **named people** who fill that role. The role title is
 * what the workshop-planner proposes and what questions get targeted at;
 * the names are a human-edited roster for invites, pre-reads, etc.
 */
export interface WorkshopAttendee {
  id: string;
  title: string;        // role title, e.g. "Head of CRM"
  names?: string[];     // optional: specific people, e.g. ["Ahmed Khan", "Sara Patel"]
}

/**
 * A workshop in the engagement inventory. One row in the Plan step's
 * spreadsheet (see the reference sheet with ID / Phase / Workshop / Track /
 * Duration / Mode / Status / Summary / Outcomes / Agenda / Attendees / …).
 */
export interface Workshop {
  id: string;
  code?: string;                       // short display id, e.g. "W01"
  phase: string;                       // "Discovery", "Alignment", "Strategy", …
  name: string;                        // short workshop name
  track?: string;                      // owner / track lead (e.g. "CX", "CRM")
  duration?: string;                   // "90 min", "2h"
  mode?: WorkshopMode;
  status: WorkshopStatus;
  summary: string;                     // 1-3 sentences: what & why
  mainOutcomes: string[];              // bullet list of deliverables/decisions
  agenda: WorkshopAgendaItem[];        // tentative agenda slots
  clientAttendees: WorkshopAttendee[]; // client-side roles (with optional names)
  agencyAttendees: WorkshopAttendee[]; // Digitas-side roles (with optional names)
  preReads: string[];                  // docs to circulate before the session
  dependencies: string[];              // cross-workstream dependencies
  notes?: string;                      // freeform
  order: number;
}

/**
 * What each workshop question is trying to surface.
 *
 * - `problem`       — surface pain points, broken workflows, conflicts
 * - `jtbd`          — surface the underlying job / motivation (JTBD)
 * - `circumstance`  — surface the situational triggers / forces that bring
 *                     this moment into being (what must be true)
 * - `context`       — grounding / scene-setting, not meant to surface signals
 * - `need`          — surface explicit needs / requested capabilities
 * - `opportunity`   — surface unclaimed territory / growth vectors
 * - `gap`           — surface what's missing between today and desired state
 * - `contradiction` — pressure-test the brief / challenge stated assumptions
 */
export type WorkshopQuestionIntent =
  | 'context'
  | 'problem'
  | 'jtbd'
  | 'circumstance'
  | 'need'
  | 'opportunity'
  | 'gap'
  | 'contradiction';

/**
 * A question attached to a workshop, targeted at a specific attendee role.
 * General enough to be asked in the room, specific enough to land a
 * Problem / JTBD / Circumstance / Need / Opportunity / Gap in signal
 * extraction later.
 */
export interface WorkshopQuestion {
  id: string;
  workshopId: string;
  targetRole: string;             // a role title from client/agency attendees
  text: string;
  intent: WorkshopQuestionIntent;
  journeyPhase?: string;          // optional: the journey phase this question probes
  rationale?: string;             // why this question, for the facilitator
  notes?: string;                 // captured answers / observations
  order: number;
  /**
   * Which input the question was inspired by. Drives the provenance chip
   * on the Discovery page.
   * - `form`     → derived only from the structured brief form (default)
   * - `brief`    → inspired by the uploaded brief document
   * - `research` → inspired by an uploaded research document
   * - `mixed`    → drew on more than one source
   *
   * Optional for backwards compatibility with questions persisted before
   * provenance tracking landed.
   */
  sourceContext?: 'form' | 'brief' | 'research' | 'mixed';
  /**
   * Per-source citations the generator surfaced when proposing the
   * question. Used by the Discovery page tooltip to show "where did this
   * come from".
   */
  sourceCitations?: {
    briefExcerpt?: string;
    researchDocId?: string;
    researchExcerpt?: string;
  };
}

// ========================================
// Extended Model Interface
// ========================================

// ========================================
// Capture & Extraction (Ingestion Layer)
// ========================================
// These entities live in IndexedDB for the prototype (files + chunks are
// too big for localStorage). The schema mirrors what would land in
// Supabase later — same shapes, same FKs — so the eventual migration is
// mechanical, not a redesign.

export type UploadKind = 'transcript' | 'notes' | 'document';
export type UploadStatus =
  | 'uploaded'       // binary written, no parsing yet
  | 'parsing'        // parse job running
  | 'parsed'         // plain text extracted
  | 'chunking'       // chunk + embed job running
  | 'ready'          // chunks + embeddings in place; ready for extraction
  | 'failed';

/**
 * A file uploaded against a workshop (transcript, draft notes, or
 * supporting document). The binary Blob lives in a dedicated IndexedDB
 * object store keyed by `blobKey`; this row holds the metadata + parsed
 * text + status.
 */
export interface Upload {
  id: string;
  modelId: string;
  workshopId: string;
  kind: UploadKind;
  filename: string;
  mimeType: string;
  fileSize: number;
  /** Key for the Blob in the IndexedDB `uploadBlobs` store. */
  blobKey: string;
  /** Plain text after parsing. Populated once status === 'parsed'. */
  parsedText?: string;
  /** SHA-256 of the file contents — used to detect duplicate uploads. */
  contentHash?: string;
  status: UploadStatus;
  error?: string;
  uploadedAt: Date;
  parsedAt?: Date;
  chunkedAt?: Date;
}

/**
 * One chunk of a parsed transcript with its embedding. Stored separately
 * so vector search can scan just the chunks table without loading the
 * rest of the Upload. Chunks are 400-600 tokens with ~50-token overlap.
 */
export interface TranscriptChunk {
  id: string;
  uploadId: string;
  modelId: string;
  chunkIndex: number;    // 0-based position within the transcript
  text: string;
  tokenCount: number;
  /** Optional if the transcript was diarized. */
  speaker?: string;
  /** Optional if the transcript was timestamped (e.g. ".vtt"). Seconds. */
  timestampStart?: number;
  timestampEnd?: number;
  /** Embedding vector. 1536 dims for text-embedding-3-small. */
  embedding?: number[];
  createdAt: Date;
}

/**
 * The kinds of LLM extraction passes the pipeline can run against an
 * upload. Each specialist skill owns one kind. Keeping them enumerated
 * means we can query "show me all the failed jtbd extractions" etc.
 */
export type ExtractionKind =
  | 'question-answers'
  | 'problems'
  | 'jtbds'
  | 'needs'
  | 'opportunities'
  | 'gaps'
  | 'initiatives'   // things the client proposed building
  | 'wishlist'      // things the client said they want
  | 'quotes'        // verbatim gold for presentations
  | 'contradictions'; // cross-upload pass — multiple uploadIds on one run

export type ExtractionStatus = 'pending' | 'running' | 'done' | 'failed';

/**
 * An extraction run. One row per (upload, kind) run — plus cross-upload
 * runs (contradictions) where uploadId is omitted. Re-runs are new rows,
 * not mutations, so the audit trail survives prompt changes.
 */
export interface Extraction {
  id: string;
  modelId: string;
  /** Omitted for cross-upload runs (contradictions, curation). */
  uploadId?: string;
  kind: ExtractionKind;
  /** Semver-ish version string for the prompt template that produced this run. */
  promptVersion: string;
  modelName: string;       // e.g. "gpt-4o", "claude-sonnet-4"
  status: ExtractionStatus;
  startedAt: Date;
  completedAt?: Date;
  error?: string;
  /** How many output rows this extraction produced (for quick UI counts). */
  outputCount?: number;
}

/**
 * A workshop-question answer backfilled from a transcript. One row per
 * (question × upload). Confidence reflects how directly the transcript
 * addressed the question. Supporting chunk IDs give provenance so the UI
 * can show the exact source quote.
 */
export interface QuestionAnswer {
  id: string;
  modelId: string;
  workshopQuestionId: string;
  extractionId: string;
  uploadId: string;
  answerText: string;
  confidence: ConfidenceLevel;
  confidenceReason?: string;
  supportingChunkIds: string[];
  /** Curation gate — user accepts/rejects before it counts as "answered". */
  accepted?: boolean;
  reviewedBy?: string;
  reviewedAt?: Date;
}

/**
 * A proto-signal extracted from a transcript. Lives in its own table
 * (not `signals`) because it's pre-curation raw output. User promotes
 * accepted ones into `Signal[]` on the Signals page.
 */
export type ExtractedSignalType =
  | 'problem'
  | 'jtbd'
  | 'need'
  | 'opportunity'
  | 'gap'
  | 'initiative'
  | 'wishlist'
  | 'quote';

export interface ExtractedSignal {
  id: string;
  modelId: string;
  extractionId: string;
  uploadId: string;
  type: ExtractedSignalType;
  text: string;
  confidence: ConfidenceLevel;
  confidenceReason?: string;
  supportingChunkIds: string[];
  /** Optional routing hints from the extractor. */
  department?: string;
  persona?: string;
  /** If promoted, the id of the curated `Signal` row this became. */
  promotedToSignalId?: string;
  dismissedAt?: Date;
  createdAt: Date;
}

// ========================================
// Problem Diagnostics (Capture phase, third folder)
// ========================================
// Curated Problem Signals (Signal rows of type='problem') get classified
// into an 8-discipline taxonomy, scored on Frequency × Impact, and mapped
// onto journey phases. Frequency is computed deterministically from
// source/department spread; Impact is LLM-rated. Editable end-to-end.
// See `.claude/skills/problem-diagnostics-framework/SKILL.md` for the
// taxonomy definitions, rubrics, and report structure.

export type ProblemDiscipline =
  | 'technical'
  | 'cx-human'
  | 'governance'
  | 'strategy-business'
  | 'ux-ui'
  | 'reporting-dashboarding'
  | 'martech'
  | 'brand';

export type DiagnosticScore = 1 | 2 | 3 | 4 | 5;

/**
 * One classified problem. FK to a curated Signal of type='problem' on
 * the Model. Frequency is deterministic; Impact is LLM-rated. Each row
 * carries rationales for transparency and to defend manual edits.
 */
export interface ProblemDiagnostic {
  id: string;
  modelId: string;
  problemSignalId: string;          // → Signal.id where type='problem'
  discipline: ProblemDiscipline;    // primary
  disciplineRationale: string;
  secondaryDiscipline?: ProblemDiscipline;
  secondaryRationale?: string;
  frequency: DiagnosticScore;       // computed client-side from source/dept spread
  frequencyRationale: string;       // computed: "4 sources across CRM, CX, Tech"
  impact: DiagnosticScore;          // LLM-rated
  impactRationale: string;
  /**
   * Phase mapping. Two semantic states:
   *  - non-empty array → phase-scoped problem. May span phases within a
   *    single journey OR across multiple journeys (e.g. a checkout
   *    breakage that hits both consumer and corporate journeys).
   *  - empty array `[]` → CROSS-CUTTING / systemic problem that does not
   *    belong to any specific phase (data sync issues, governance
   *    ambiguity, reporting gaps, brand voice drift). The UI surfaces
   *    these in a separate "Cross-cutting issues" banner so they are
   *    visible regardless of the active journey filter.
   *
   * Empty is meaningful — never auto-fill with `journeyPhases[0]`.
   */
  affectedPhaseIds: string[];
  phaseRationale: string;
  manuallyEdited: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * The narrative report generated from a complete set of diagnostics.
 * One row per model (overwritten on each regenerate). Stored separately
 * so editing diagnostics doesn't auto-invalidate the report — the
 * strategist regenerates explicitly.
 */
export interface ProblemDiagnosticNarrative {
  id: string;
  modelId: string;
  executiveSummary: string;
  perDiscipline: Array<{
    discipline: ProblemDiscipline;
    narrative: string;
  }>;
  perPhase: Array<{
    phaseId: string;
    narrative: string;
  }>;
  perQuadrant: {
    quickWins: string;       // low freq, high impact
    majorProjects: string;   // high freq, high impact
    timeSinks: string;       // high freq, low impact
    minor: string;           // low freq, low impact
  };
  generatedAt: Date;
}

// API response types for the diagnostics pipeline
export interface ClassifyProblemsResponseItem {
  problemSignalId: string;
  discipline: ProblemDiscipline;
  disciplineRationale: string;
  secondaryDiscipline?: ProblemDiscipline;
  secondaryRationale?: string;
  impact: DiagnosticScore;
  impactRationale: string;
  /** See ProblemDiagnostic.affectedPhaseIds — `[]` means cross-cutting. */
  affectedPhaseIds: string[];
  phaseRationale: string;
}

export interface ClassifyProblemsResponse {
  promptVersion: string;
  modelName: string;
  diagnostics: ClassifyProblemsResponseItem[];
}

export interface DiagnoseNarrativeResponse {
  promptVersion: string;
  modelName: string;
  narrative: Omit<ProblemDiagnosticNarrative, 'id' | 'modelId' | 'generatedAt'>;
}
