// Core types for Journey Generator

export type ExperienceType = 'product' | 'marketing' | 'service';

/**
 * A top-level journey on a model. A model can contain several journeys
 * (for example an airport model has Arrival, Transit, Departure) and each
 * journey has its own JTBD blueprint — a one-liner that frames what the
 * customer is fundamentally trying to do during that journey. Journey
 * phases, demand spaces, dimensions, and activations are all scoped to a
 * single journey via `JourneyPhase.journeyId`.
 */
export interface Journey {
  id: string;
  name: string;
  jtbdBlueprint: string;
  order: number;
}

export interface JourneyPhase {
  id: string;
  /**
   * The journey this phase belongs to. Optional at the type level only to
   * keep backwards compatibility with pre-multi-journey models loaded
   * from localStorage; the store's migration stamps legacy phases on
   * hydration so in practice every phase in the store has a journeyId.
   */
  journeyId?: string;
  label: string;
  description: string;
  trigger: string; // What event marks entry into this phase
  order: number;
  /**
   * Where this phase came from.
   * - `user`      → user typed or preloaded the phase in the brief (e.g. Dubai Airport example)
   * - `ai`        → generated by the journey-phases endpoint
   * - `discovery` → proposed from discovery evidence/signals
   * Optional for backwards compatibility with older models.
   */
  source?: 'user' | 'ai' | 'discovery';
}

export interface DemandSpace {
  id: string;
  journeyPhaseId: string;
  label: string; // 2-4 words
  jobToBeDone: string; // "When I [situation], I want to [action], so that [outcome]"
  description?: string; // Optional 2-3 sentences (kept for backwards compatibility)
  order: number;
}

/**
 * A Circumstance is a composite position across the 5 universal axes
 * (Knowledge, Intent, Composition, Constraint, Moment) plus a narrative
 * JTBD-formatted statement and the Struggle/Progress forces. Each demand
 * space gets exactly 5 Circumstances, and collectively they must cover
 * contrast on every axis (e.g. at least one Novice + one Expert).
 */
export interface Circumstance {
  id: string;
  demandSpaceId: string;
  order: number;
  // Axis tuple — one value per axis
  knowledge: string;     // e.g. "Expert"
  intent: string;        // e.g. "Routine"
  composition: string;   // e.g. "Solo"
  constraint: string;    // e.g. "Time"
  moment: string;        // e.g. "Long-haul business travel"
  // Narrative (assembled as "When I am [context], I want to [action], so that [outcome].")
  context: string;       // "flying alone on a long-haul overnight work trip and already know what content unwinds me"
  action: string;        // "quickly access familiar entertainment options"
  outcome: string;       // "relax fast and make the journey feel shorter"
  // Forces framework
  struggle: string;      // "The system slows me down when I already know what I want."
  progress: string;      // "Get into rest mode quickly and reduce the mental drag of travel."
  // Optional provenance (matches existing signal-backed pattern)
  supportingSignalIds?: string[];
  evidence?: 'signal-backed' | 'brief-only';
}

// Tech stack tool with purpose
export interface TechTool {
  id: string;
  value: string;     // Tool name
  purpose?: string;  // What this tool is used for
}

// Tech stack structured input - each field supports multiple selections
export interface TechStack {
  cloudWarehouse?: TechTool[];     // e.g., Snowflake, BigQuery, Redshift, Databricks
  dataStorage?: TechTool[];        // e.g., AWS S3, Azure Blob, PostgreSQL, MongoDB
  crm?: TechTool[];                // e.g., Salesforce, HubSpot, Microsoft Dynamics
  cdp?: TechTool[];                // e.g., Segment, mParticle, Tealium, Adobe CDP
  cep?: TechTool[];                // e.g., Braze, Emarsys, SFMC, Iterable
  dxp?: TechTool[];                // e.g., Optimizely, Adobe Experience Manager, Sitecore
  aiModels?: TechTool[];           // e.g., GPT-4, Claude, Gemini, Llama
  aiPlatform?: TechTool[];         // e.g., Azure AI Foundry, AWS Bedrock, Vertex AI
}

// Product/channel with description
export interface Product {
  id: string;
  name: string;        // e.g., "Mobile App", "Website", "Kiosk"
  description: string; // What this product/channel does
}

// Target persona
export interface Persona {
  id: string;
  label: string;       // e.g., "Budget-conscious families"
}

// Persona mapping - links personas to demand spaces and circumstances per phase
export interface PersonaPhaseMapping {
  phaseId: string;
  demandSpaceIds: string[];    // Demand spaces in this phase for this persona
  circumstanceIds: string[];   // Circumstances in this phase for this persona
}

export interface PersonaMapping {
  personaId: string;
  mappingsByPhase: PersonaPhaseMapping[];  // Phase-structured mappings (one entry per phase)
}

// User-defined phase (before generation)
export interface CustomJourneyPhase {
  label: string;
  description: string;
  trigger?: string;
}

export interface ModelInput {
  experienceTypes: ExperienceType[];  // Now supports multiple selection
  industry: string;
  businessDescription: string;
  techStack?: TechStack;
  products?: Product[];
  channels?: string[];
  personas?: Persona[];
  painPoints?: string;  // Now a textarea (multi-line)
  customJourneyPhases?: CustomJourneyPhase[];  // Optional: user can mandate phases instead of generating them
}

// Activation types - what to do for each Demand Space × Circumstance combination.
// NOTE: Activation generation is currently deferred — the APIs have not yet
// been migrated from the old dimension-value model to the new Circumstance
// model. These types reflect the target shape (one activation per
// Circumstance) even though generation is temporarily disabled in the UI.

// Marketing: 6 CRM levers
export interface MarketingActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  messageDepth: string; // awareness, consideration, action
  urgency: string; // low, medium, high
  channel: string; // email, SMS, push, in-app, etc.
  tone: string; // informative, empathetic, urgent, celebratory
  offer: string; // what to offer
  cadence: string; // frequency and timing
}

// Product: Features that become user stories
export interface ProductActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  feature: string; // feature name
  description: string; // what it does
  userStory: string; // As a... I want... So that...
  priority: 'high' | 'medium' | 'low';
}

// Service: Agent tools and knowledge
export interface ServiceActivation {
  id: string;
  demandSpaceId: string;
  circumstanceId: string;
  tools: string; // tools/systems to use
  knowledge: string; // knowledge articles to surface
  c360Signals: string; // customer 360 data points to show
  handoffRules: string; // when/how to escalate or transfer
}

export interface Model {
  id: string;
  input: ModelInput;
  /**
   * Top-level journeys on this model (Arrival / Transit / Departure, etc.).
   * Always present on newly created models. Older models (from before
   * multi-journey support landed) may be missing this field on disk;
   * the store rehydration migrates them into a single default journey.
   */
  journeys: Journey[];
  journeyPhases: JourneyPhase[];
  demandSpaces: DemandSpace[];
  circumstances: Circumstance[]; // 5 composite circumstances per demand space
  marketingActivations: MarketingActivation[];
  productActivations: ProductActivation[];
  serviceActivations: ServiceActivation[];
  personaMappings: PersonaMapping[]; // Persona filtering

  // Discovery & Signal Mapping (Phase 1)
  discoveryPlan?: DiscoveryPlan;
  evidenceRecords?: Evidence[];
  signals?: Signal[];
  mappings?: Mapping[];
  proposals?: Proposal[];
  discoveryBundle?: DiscoveryBundle;
  currentStep?: ConsultancyStep;

  // Workshop inventory (Plan step)
  workshops?: Workshop[];
  workshopQuestions?: WorkshopQuestion[];

  createdAt: Date;
  updatedAt: Date;
}

// API response types
export interface GenerateJourneyPhasesResponse {
  journeyPhases: Omit<JourneyPhase, 'id' | 'order'>[];
}

// Demand spaces response - no longer includes circumstances
export interface GenerateDemandSpacesResponse {
  demandSpaces: {
    label: string;
    jobToBeDone: string;
    description?: string;
  }[];
}

// Circumstances response - exactly 5 circumstances per demand space × phase
// crossing. Each circumstance is a composite across all 5 universal axes
// plus a JTBD-formatted narrative and Struggle/Progress forces.
export interface GenerateCircumstancesResponse {
  circumstances: {
    knowledge: string;
    intent: string;
    composition: string;
    constraint: string;
    moment: string;
    context: string;
    action: string;
    outcome: string;
    struggle: string;
    progress: string;
    supportingSignalIds?: string[];
    evidence?: 'signal-backed' | 'brief-only';
  }[];
}

// Activation response types (deferred migration — see note above).
export interface GenerateMarketingActivationsResponse {
  activations: {
    circumstanceLabel: string;
    messageDepth: string;
    urgency: string;
    channel: string;
    tone: string;
    offer: string;
    cadence: string;
  }[];
}

export interface GenerateProductActivationsResponse {
  activations: {
    circumstanceLabel: string;
    feature: string;
    description: string;
    userStory: string;
    priority: string;
  }[];
}

export interface GenerateServiceActivationsResponse {
  activations: {
    circumstanceLabel: string;
    tools: string;
    knowledge: string;
    c360Signals: string;
    handoffRules: string;
  }[];
}

// Persona mapping response
export interface MapPersonasResponse {
  personaMappings: {
    personaId: string;
    mappingsByPhase: {
      phaseId: string;
      demandSpaceIds: string[];
      circumstanceIds: string[];
    }[];
  }[];
}

// ========================================
// Discovery & Signal Mapping Types (Phase 1)
// ========================================

// Evidence types (from discovery-framework skill)
export type EvidenceType = 'interview' | 'workshop' | 'document' | 'quote' | 'metric' | 'observation' | 'artifact';
export type ConfidenceLevel = 'high' | 'medium' | 'low';

export interface Evidence {
  id: string;
  type: EvidenceType;
  department: string;
  source: string;
  date: Date;
  summary: string;
  rawText?: string;
  tags: string[];
  confidence: ConfidenceLevel;
  confidenceReason: string;
  contradicts?: string[]; // Evidence IDs this contradicts
}

// Signal types (from signal-mapping-framework skill)
export type SignalType = 'problem' | 'need' | 'opportunity' | 'gap';

export interface SignalSource {
  evidenceId: string;
  quote?: string;
}

export interface Signal {
  id: string;
  type: SignalType;
  text: string;
  department: string;
  sources: SignalSource[];
  relatedSignalIds?: string[];
  confidence: ConfidenceLevel;
  confidenceReason: string;
  proposedAction?: string;
}

// Discovery Plan types (from discovery-question-generator agent)
export type DiscoveryPriority = 'must-have' | 'should-have' | 'skip';

export interface DiscoveryPlanInterview {
  department: string;
  role: string;
  priority: DiscoveryPriority;
  duration: string;
  questions: string[];
  capture: string[]; // Documents to request
}

export interface DiscoveryPlanWorkshop {
  name: string;
  participants: string[];
  duration: string;
  priority: DiscoveryPriority;
  objective: string;
}

export interface DiscoveryPlanDocument {
  title: string;
  askedOf: string;
  priority: DiscoveryPriority;
}

export interface DiscoveryPlan {
  plan: {
    interviews: DiscoveryPlanInterview[];
    workshops: DiscoveryPlanWorkshop[];
    documents: DiscoveryPlanDocument[];
  };
  coverage: {
    departments: Record<string, DiscoveryPriority>;
    risks: string[];
  };
  timelineEstimate: string;
}

// Mapping & Proposal types (from mapper-agent)
export type MappingTargetKind = 'phase' | 'demandSpace' | 'circumstance' | 'activation';

export interface Mapping {
  signalId: string;
  action: 'map';
  target: {
    kind: MappingTargetKind;
    id: string;
  };
  rationale: string;
  conflictFlag?: boolean;
}

export interface Proposal {
  signalIds: string[];
  action: 'propose';
  kind: MappingTargetKind;
  payload: unknown; // Entity-specific shape (phase, demandSpace, dimension, etc.)
  justification: {
    reasoning: string;
    confidence: ConfidenceLevel;
    confidenceReason: string;
  };
  status: 'proposed';
}

// Discovery Bundle - approved evidence + signals ready for generation
export interface DiscoveryBundle {
  approvedEvidence: Evidence[];
  candidateSignals: {
    problems: Signal[];
    needs: Signal[];
    opportunities: Signal[];
    gaps: Signal[];
  };
  approvedBy: string;
  approvedAt: Date;
}

// Consultancy workflow step
export type ConsultancyStep = 'brief' | 'plan' | 'capture' | 'signals' | 'review' | 'landscape';

// ========================================
// Workshop Inventory (Plan step)
// ========================================

export type WorkshopMode = 'onsite' | 'hybrid' | 'remote';
export type WorkshopStatus =
  | 'draft'
  | 'proposed'
  | 'scheduled'
  | 'done'
  | 'skipped';

/** One slot within a workshop's tentative agenda. */
export interface WorkshopAgendaItem {
  id: string;
  label: string;        // "Context-set + role framing"
  duration?: string;    // "15 min", "0:45"
  notes?: string;       // facilitator guidance, sticky-note prompts, etc.
}

/**
 * An attendee slot on a workshop: a **role title** (always) plus an
 * optional list of **named people** who fill that role. The role title is
 * what the workshop-planner proposes and what questions get targeted at;
 * the names are a human-edited roster for invites, pre-reads, etc.
 */
export interface WorkshopAttendee {
  id: string;
  title: string;        // role title, e.g. "Head of CRM"
  names?: string[];     // optional: specific people, e.g. ["Ahmed Khan", "Sara Patel"]
}

/**
 * A workshop in the engagement inventory. One row in the Plan step's
 * spreadsheet (see the reference sheet with ID / Phase / Workshop / Track /
 * Duration / Mode / Status / Summary / Outcomes / Agenda / Attendees / …).
 */
export interface Workshop {
  id: string;
  code?: string;                       // short display id, e.g. "W01"
  phase: string;                       // "Discovery", "Alignment", "Strategy", …
  name: string;                        // short workshop name
  track?: string;                      // owner / track lead (e.g. "CX", "CRM")
  duration?: string;                   // "90 min", "2h"
  mode?: WorkshopMode;
  status: WorkshopStatus;
  summary: string;                     // 1-3 sentences: what & why
  mainOutcomes: string[];              // bullet list of deliverables/decisions
  agenda: WorkshopAgendaItem[];        // tentative agenda slots
  clientAttendees: WorkshopAttendee[]; // client-side roles (with optional names)
  agencyAttendees: WorkshopAttendee[]; // Digitas-side roles (with optional names)
  preReads: string[];                  // docs to circulate before the session
  dependencies: string[];              // cross-workstream dependencies
  notes?: string;                      // freeform
  order: number;
}

/**
 * What each workshop question is trying to surface.
 *
 * - `problem`       — surface pain points, broken workflows, conflicts
 * - `jtbd`          — surface the underlying job / motivation (JTBD)
 * - `circumstance`  — surface the situational triggers / forces that bring
 *                     this moment into being (what must be true)
 * - `context`       — grounding / scene-setting, not meant to surface signals
 * - `need`          — surface explicit needs / requested capabilities
 * - `opportunity`   — surface unclaimed territory / growth vectors
 * - `gap`           — surface what's missing between today and desired state
 * - `contradiction` — pressure-test the brief / challenge stated assumptions
 */
export type WorkshopQuestionIntent =
  | 'context'
  | 'problem'
  | 'jtbd'
  | 'circumstance'
  | 'need'
  | 'opportunity'
  | 'gap'
  | 'contradiction';

/**
 * A question attached to a workshop, targeted at a specific attendee role.
 * General enough to be asked in the room, specific enough to land a
 * Problem / JTBD / Circumstance / Need / Opportunity / Gap in signal
 * extraction later.
 */
export interface WorkshopQuestion {
  id: string;
  workshopId: string;
  targetRole: string;             // a role title from client/agency attendees
  text: string;
  intent: WorkshopQuestionIntent;
  journeyPhase?: string;          // optional: the journey phase this question probes
  rationale?: string;             // why this question, for the facilitator
  notes?: string;                 // captured answers / observations
  order: number;
}

// ========================================
// Extended Model Interface
// ========================================
