// Mock data for the Journey Generator prototype — Disney / Theme Parks example.
// Matches the schema from lib/types.ts in the source codebase.

window.MOCK_MODEL = {
  input: {
    experienceTypes: ['marketing'],
    industry: 'Theme Parks & Attractions',
    businessDescription:
      'Walt Disney World is a destination resort in Orlando comprising four theme parks, two water parks, and resort hotels. The challenge is maximizing guest lifetime value by driving multi-day stays, park-hopping, and per-guest spend on dining, merchandise, and premium experiences.',
  },
  phases: [
    {
      id: 'p1', order: 1, label: 'Dream & Discover', accent: '#6366f1',
      trigger: 'Engagement with Disney content online or through word-of-mouth recommendations.',
      counts: { spaces: 12, dims: 52, values: 141 },
    },
    {
      id: 'p2', order: 2, label: 'Plan & Book', accent: '#06b6d4',
      trigger: 'Initiation of trip planning via Disney Experience App or DisneyWorld.com.',
      counts: { spaces: 12, dims: 50, values: 141 },
    },
    {
      id: 'p3', order: 3, label: 'Pre-Arrival Optimization', accent: '#10b981',
      trigger: 'Confirmation of trip purchase and accommodation booking.',
      counts: { spaces: 12, dims: 50, values: 137 },
    },
    {
      id: 'p4', order: 4, label: 'Magic in Motion', accent: '#f59e0b',
      trigger: 'Scanning of MagicBand or park ticket at the entrance gates.',
      counts: { spaces: 12, dims: 49, values: 128 },
    },
    {
      id: 'p5', order: 5, label: 'Enrichment & Exploration', accent: '#ec4899',
      trigger: 'Completion of initial park entry and exploration of additional offerings.',
      counts: { spaces: 12, dims: 53, values: 135 },
    },
    {
      id: 'p6', order: 6, label: 'Reflect & Share', accent: '#8b5cf6',
      trigger: 'Post-visit reflection, photo sharing, and renewal of loyalty behaviors.',
      counts: { spaces: 11, dims: 42, values: 116 },
    },
  ],
  // Demand spaces per phase (keyed by phase.id) — just enough to fill the canvas.
  spaces: {
    p1: [
      { id: 's1-1', label: 'Create Lasting Memories',
        jtbd: 'When I think about family vacations, I want to create experiences that live in our photos and stories for years.',
        dims: [
          { label: 'Familiarity', desc: 'How well past visitors know Disney World and its offerings', values: ['First-time visitor', 'Returning guest', 'Disney enthusiast'] },
          { label: 'Group', desc: 'Who they\'re planning to come with', values: ['Parents with young kids', 'Multi-generational', 'Friends group'] },
          { label: 'Economic', desc: 'Budget context for the trip', values: ['Budget-conscious', 'Premium seeker'] },
          { label: 'Moment', desc: 'Life context driving the visit', values: ['Milestone birthday', 'Back-to-school break'] },
        ],
        tall: true,
      },
      { id: 's1-2', label: 'Reconnect with Childhood',
        jtbd: 'When I choose a vacation destination, I want to relive fond memories and share them with people I love.',
        dims: [
          { label: 'Nostalgia', desc: '', values: ['Classic fan', 'Parent sharing', 'Collector'] },
          { label: 'Group', desc: '', values: ['Solo', 'Couple', 'Multi-gen'] },
          { label: 'Familiarity', desc: '', values: ['Expert', 'Returning'] },
          { label: 'Occasion', desc: '', values: ['Anniversary', 'Reunion'] },
        ],
      },
      { id: 's1-3', label: 'Celebrate Milestones',
        jtbd: 'When I plan a special-occasion trip, I want to find extraordinary ways to mark the moment.',
        dims: [
          { label: 'Occasion', desc: '', values: ['Wedding', 'Birthday', 'Graduation'] },
          { label: 'Group', desc: '', values: ['Couple', 'Family', 'Large group'] },
          { label: 'Economic', desc: '', values: ['Premium seeker', 'Corporate'] },
          { label: 'Composition', desc: '', values: ['Multi-party', 'Single party'] },
          { label: 'Urgency', desc: '', values: ['Months-out planning'] },
        ],
      },
      { id: 's1-4', label: 'Secure Hassle-Free Travel',
        jtbd: 'When I coordinate a family trip, I want tools that reduce planning friction across many decisions.',
        dims: [
          { label: 'Urgency', desc: '', values: ['Relaxed', 'Time-constrained'] },
          { label: 'Mobility', desc: '', values: ['Full mobility', 'Stroller', 'Wheelchair'] },
          { label: 'Knowledge', desc: '', values: ['First-timer', 'Experienced planner'] },
          { label: 'Composition', desc: '', values: ['Small group', 'Large group'] },
        ],
      },
    ],
    p2: [
      { id: 's2-1', label: 'Culinary Exploration',
        jtbd: 'When I choose dining options, I want to explore diverse and exciting cuisines.',
        dims: [
          { label: 'Intent', desc: '', values: ['Signature dining', 'Quick-serve', 'Character meal'] },
          { label: 'Group', desc: '', values: ['Kids at table', 'Adults only'] },
          { label: 'Dietary', desc: '', values: ['Vegetarian', 'Allergen-aware'] },
          { label: 'Occasion', desc: '', values: ['Birthday', 'Anniversary'] },
        ],
      },
      { id: 's2-2', label: 'Maximize Family Joy',
        jtbd: 'When I book our theme park tickets, I want to ensure there\'s something for everyone.',
        dims: [
          { label: 'Group', desc: '', values: ['Toddlers', 'Tweens', 'Teens'] },
          { label: 'Intent', desc: '', values: ['Rides-first', 'Character-first', 'Balanced'] },
          { label: 'Economic', desc: '', values: ['Budget', 'Premium'] },
          { label: 'Knowledge', desc: '', values: ['First-timer', 'Veteran'] },
        ],
        tall: true,
      },
      { id: 's2-3', label: 'Capture Magical Moments',
        jtbd: 'When I\'m preparing for our vacation, I want to plan for unique and Instagrammable experiences.',
        dims: [
          { label: 'Sharing', desc: '', values: ['Social creator', 'Private album'] },
          { label: 'Style', desc: '', values: ['Character-forward', 'Scenery-forward'] },
          { label: 'Moment', desc: '', values: ['Birthday', 'Anniversary'] },
        ],
      },
      { id: 's2-4', label: 'Anticipate Every Need',
        jtbd: 'When I confirm our stay, I want pre-departure planning that accounts for the whole trip.',
        dims: [
          { label: 'Knowledge', desc: '', values: ['First-timer', 'Expert'] },
          { label: 'Composition', desc: '', values: ['Small family', 'Extended family'] },
          { label: 'Urgency', desc: '', values: ['Months out', 'Weeks out'] },
        ],
      },
    ],
    p3: [
      { id: 's3-1', label: 'Effortless Adventure Planning',
        jtbd: 'When I finalize my travel dates, I want to plan my family\'s activities without decision fatigue.',
        dims: [
          { label: 'Knowledge', desc: '', values: ['First-timer', 'Returning'] },
          { label: 'Composition', desc: '', values: ['Young kids', 'Teens'] },
          { label: 'Moment', desc: '', values: ['Summer', 'Holiday'] },
        ],
        tall: true,
      },
      { id: 's3-2', label: 'Memorable Moments',
        jtbd: 'When I book our theme park tickets, I want to create unforgettable memories with loved ones.',
        dims: [
          { label: 'Group', desc: '', values: ['Nuclear family', 'Multi-gen'] },
          { label: 'Occasion', desc: '', values: ['Birthday', 'Anniversary'] },
          { label: 'Economic', desc: '', values: ['Budget', 'Premium'] },
          { label: 'Style', desc: '', values: ['Relaxed', 'Pack it in'] },
        ],
      },
      { id: 's3-3', label: 'Family Connection',
        jtbd: 'When I\'m with my family in the park, I want to be fully present with them.',
        dims: [
          { label: 'Group', desc: '', values: ['Parents with kids', 'Grandparents'] },
          { label: 'Mobility', desc: '', values: ['Stroller', 'Full mobility'] },
          { label: 'Intent', desc: '', values: ['Relaxation-first', 'Experience-first'] },
        ],
      },
    ],
    p4: [
      { id: 's4-1', label: 'Effortless Exploration',
        jtbd: 'When I first enter the park, I want to explore freely and discover what\'s around me.',
        dims: [
          { label: 'Knowledge', desc: '', values: ['First-timer', 'Veteran'] },
          { label: 'Group', desc: '', values: ['Couple', 'Family'] },
          { label: 'Mobility', desc: '', values: ['Full', 'Stroller', 'Wheelchair'] },
        ],
        tall: true,
      },
      { id: 's4-2', label: 'Maximize Experience',
        jtbd: 'When I\'m in the park, I want to make the most of my time and money.',
        dims: [
          { label: 'Intent', desc: '', values: ['Rides-max', 'Shows-max', 'Balanced'] },
          { label: 'Economic', desc: '', values: ['Genie+ user', 'Standby-only'] },
          { label: 'Urgency', desc: '', values: ['Single-day', 'Multi-day'] },
        ],
      },
      { id: 's4-3', label: 'Spontaneous Discovery',
        jtbd: 'When I am in a new environment, I want to explore without a rigid plan.',
        dims: [
          { label: 'Style', desc: '', values: ['Wanderer', 'Planner-light'] },
          { label: 'Group', desc: '', values: ['Solo', 'Couple'] },
          { label: 'Moment', desc: '', values: ['Afternoon lull', 'Evening'] },
        ],
      },
    ],
    p5: [
      { id: 's5-1', label: 'Maximize Every Moment',
        jtbd: 'When I am on a once-in-a-lifetime trip, I want to make the most of every opportunity.',
        dims: [
          { label: 'Intent', desc: '', values: ['Thrill seeker', 'Show lover'] },
          { label: 'Knowledge', desc: '', values: ['Insider', 'Guided'] },
          { label: 'Economic', desc: '', values: ['Upgrade-open', 'Frugal'] },
          { label: 'Composition', desc: '', values: ['Small party', 'Large party'] },
          { label: 'Mobility', desc: '', values: ['Full', 'Limited'] },
        ],
        tall: true,
      },
      { id: 's5-2', label: 'Family Bonding Adventure',
        jtbd: 'When I travel with family, I want to create shared experiences we\'ll talk about forever.',
        dims: [
          { label: 'Group', desc: '', values: ['Nuclear', 'Multi-gen'] },
          { label: 'Intent', desc: '', values: ['Ride-focused', 'Character-focused'] },
          { label: 'Moment', desc: '', values: ['Reunion', 'Celebration'] },
        ],
      },
      { id: 's5-3', label: 'Cultural Immersion',
        jtbd: 'When I visit a new place, I want to immerse myself in its unique culture and stories.',
        dims: [
          { label: 'Curiosity', desc: '', values: ['Deep dive', 'Taster'] },
          { label: 'Style', desc: '', values: ['Guided', 'Self-paced'] },
          { label: 'Composition', desc: '', values: ['Couple', 'Solo'] },
          { label: 'Moment', desc: '', values: ['Festival', 'Off-season'] },
        ],
      },
    ],
    p6: [
      { id: 's6-1', label: 'Relive the Magic',
        jtbd: 'When I return home, I want ways to keep the magic alive and plan the next trip.',
        dims: [
          { label: 'Loyalty', desc: '', values: ['One-time', 'Returning', 'AP holder'] },
          { label: 'Sharing', desc: '', values: ['Social-heavy', 'Private'] },
          { label: 'Moment', desc: '', values: ['Immediately after', 'Seasonal'] },
        ],
        tall: true,
      },
      { id: 's6-2', label: 'Capture & Share the Story',
        jtbd: 'When I come back from my trip, I want to turn it into content that tells our story.',
        dims: [
          { label: 'Sharing', desc: '', values: ['Instagram', 'Family album', 'Blog'] },
          { label: 'Style', desc: '', values: ['Curated', 'Raw'] },
        ],
      },
      { id: 's6-3', label: 'Brand Loyalty',
        jtbd: 'When I reflect on great experiences, I want the brand to stay in my life through the year.',
        dims: [
          { label: 'Loyalty', desc: '', values: ['Annual pass', 'Merch', 'Club 33'] },
          { label: 'Moment', desc: '', values: ['Holiday', 'Birthday'] },
        ],
      },
    ],
  },
};
